### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by ccneli** [mjk2244/pro-football-reference-web-scraper#48]
When I run the following code as displayed in the ReadMe:

from pro_football_reference_web_scraper import player_game_log as p

game_log = p.get_player_game_log('Josh Allen', 'QB', 2022)
print(game_log)

I get the following error:

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by mjk2244** [comment]
Thanks for pointing this out. It looks like PFR changed something with their underlying naming conventions. Should be an easy fix. Will try to find some time this week and push the change

**Comment by mjk2244** [comment]
@ccneli Issue should be fixed. Run `pip3 install --upgrade pro_football_reference_web_scraper` from the command line and try again. Let me know if you still have issues.

**Comment by bridger217** [comment]
FYI, you'll see this error when you get rate limited.
